# Generated by Django 3.0 on 2020-07-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='name',
            new_name='username',
        ),
    ]
