# Generated by Django 3.0 on 2020-07-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_auto_20200709_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='sign',
        ),
    ]
